apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-serving
  namespace: ml-training
  labels:
    app: model-serving
    project: mlops-pytorch-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-serving
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: model-serving
    spec:
      containers:
        - name: server
          image: mlops-serve:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: checkpoints-pvc
              mountPath: /app/checkpoints
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: checkpoints-pvc
          persistentVolumeClaim:
            claimName: training-checkpoints-pvc
            readOnly: true
